[phases.setup]
nixPkgs = ["nodejs_18", "openssl"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate"]

[start]
cmd = "npx prisma db push --skip-generate && node src/index.js"
